name: 'Build MacDown Archive'
description: 'Builds MacDown universal binary with optional code signing'
inputs:
  enable-signing:
    description: 'Enable code signing (true/false)'
    required: false
    default: 'false'
  team-id:
    description: 'Apple Team ID (required if signing enabled)'
    required: false
  marketing-version:
    description: 'Marketing version for CFBundleShortVersionString (e.g., 3000.0.0-beta.2)'
    required: false
    default: ''
  build-number:
    description: 'Build number for CFBundleVersion (e.g., 142)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Build MacDown archive
      shell: bash
      run: |
        echo "🔨 Building MacDown..."
        set -o pipefail

        # Build version settings (only if provided)
        VERSION_ARGS=""
        if [ -n "${{ inputs.marketing-version }}" ]; then
          VERSION_ARGS="MARKETING_VERSION=${{ inputs.marketing-version }}"
          echo "📌 Setting marketing version: ${{ inputs.marketing-version }}"
        fi
        if [ -n "${{ inputs.build-number }}" ]; then
          VERSION_ARGS="$VERSION_ARGS CURRENT_PROJECT_VERSION=${{ inputs.build-number }}"
          echo "📌 Setting build number: ${{ inputs.build-number }}"
        fi

        # Build with or without signing
        if [ "${{ inputs.enable-signing }}" == "true" ]; then
          echo "Building with code signing..."
          xcodebuild archive \
            -workspace "MacDown 3000.xcworkspace" \
            -scheme MacDown \
            -configuration Release \
            -archivePath build/MacDown.xcarchive \
            -arch arm64 -arch x86_64 \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGN_IDENTITY="Developer ID Application" \
            CODE_SIGN_STYLE="Manual" \
            DEVELOPMENT_TEAM="${{ inputs.team-id }}" \
            ENABLE_HARDENED_RUNTIME=YES \
            $VERSION_ARGS \
            | tee build.log
        else
          echo "Building without code signing (verification only)..."
          xcodebuild archive \
            -workspace "MacDown 3000.xcworkspace" \
            -scheme MacDown \
            -configuration Release \
            -archivePath build/MacDown.xcarchive \
            -arch arm64 -arch x86_64 \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            $VERSION_ARGS \
            | tee build.log
        fi

        echo "✅ Build completed"

    - name: Extract application bundle
      shell: bash
      run: |
        echo "📦 Extracting application bundle..."

        # Extract .app from archive
        cp -R build/MacDown.xcarchive/Products/Applications/"MacDown 3000.app" build/"MacDown 3000.app"

        # Display build info
        echo "Build contents:"
        ls -lh build/

        # Get version
        APP_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" build/"MacDown 3000.app"/Contents/Info.plist)
        echo "📌 App version: $APP_VERSION"
